name: Test

on: [push, pull_request]

jobs:
  test:
    timeout-minutes: 25

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      # - name: Install Node.js and NPM
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      #     cache: npm

      - name: install.sh Podman
        run: |
          ./install.sh
