name: Test

on: [push, pull_request]

jobs:
  test:
    timeout-minutes: 25

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        # os: [ubuntu-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      # - name: Install Node.js and NPM
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      #     cache: npm

      # https://docs.github.com/en/actions/learn-github-actions/variables for GITHUB_PATH
      - name: install.sh Podman
        run: |
          Invoke-WebRequest -Uri https://github.com/containers/podman/releases/download/v4.4.1/podman-v4.4.1.msi -OutFile .\podman-v4.4.1.msi
          msiexec /a .\podman-v4.4.1.msi /qn /lv .\log.txt
          bash -c "cat log.txt"
        # run: |
        #   if [ "$RUNNER_OS" == "Linux" ]; then
        #       ./install-ubuntu.sh
        #   elif [ "$RUNNER_OS" == "Windows" ]; then
        #      .\install-windows.sh
        #   elif [ "$RUNNER_OS" == "macOS" ]; then
        #       ./install-mac.sh
        #       echo "/opt/podman/bin" >> $GITHUB_PATH
        #   else
        #       echo "$RUNNER_OS not supported"
        #       exit 1
        #   fi

      # On macOS, podman machine init is required before version and info work
      - name: Podman machine init (macOS and Windows)
        run: |
          podman machine init
          podman machine start
        # run: |
        #   if [ "$RUNNER_OS" == "Windows" ]; then
        #       podman machine init
        #       podman machine start
        #   elif [ "$RUNNER_OS" == "macOS" ]; then
        #       podman machine init
        #       podman machine start
        #   else
        #       exit 0
        #   fi

      - name: Podman version
        run: |
          podman version

      - name: Podman info
        run: |
          podman info

      - name: Podman run speedometer cpu
        run: |
          podman run ghcr.io/nicenode/speedometer -t time
