name: Test

on: [push, pull_request]

jobs:
  test:
    timeout-minutes: 25

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      # - name: Install Node.js and NPM
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      #     cache: npm

      - name: install.sh Podman
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              ./install-ubuntu.sh
          elif [ "$RUNNER_OS" == "Windows" ]; then
              echo "No Windows in install-podman-sh yet"
          elif [ "$RUNNER_OS" == "macOS" ]; then
              ./install-mac.sh
          else
              echo "$RUNNER_OS not supported"
              exit 1
          fi
      
      - name: Podman version
        run: |
          podman version

      - name: Podman info
        run: |
          podman info


      - name: Podman run speedometer cpu
        run: |
          podman run ghcr.io/nicenode/speedometer -t time
